//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduFormManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class action{
        public action()
        {
            this.edu_log = new HashSet<edu_log>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
    
        public virtual ICollection<edu_log> edu_log { get; set; }
    }
}
