//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduFormManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class edu_kind{
        public edu_kind()
        {
            this.edus = new HashSet<edu>();
            this.forms = new HashSet<form>();
        }
    
        public int edu_kind_id { get; set; }
        public string name { get; set; }
    
    	public override string ToString() { return this.name; }
    
        public virtual ICollection<edu> edus { get; set; }
        public virtual ICollection<form> forms { get; set; }
    }
}
