//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduFormManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class form
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public form()
        {
            this.edu_form_data = new HashSet<edu_form_data>();
            this.mm_regular__summary_form = new HashSet<mm_regular__summary_form>();
            this.mm_regular__summary_form1 = new HashSet<mm_regular__summary_form>();
            this.municipality_form_data = new HashSet<municipality_form_data>();
            this.queries = new HashSet<query>();
            this.edu_kind = new HashSet<edu_kind>();
        }
    
        public int form_id { get; set; }
        public string name { get; set; }
        public System.DateTime submission_date { get; set; }
        public string check_file_md5 { get; set; }
        public int form_type_id { get; set; }
        public byte[] check_file_data { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<edu_form_data> edu_form_data { get; set; }
        public virtual templated_form_data templated_form_data { get; set; }
        public virtual form_type form_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mm_regular__summary_form> mm_regular__summary_form { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mm_regular__summary_form> mm_regular__summary_form1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<municipality_form_data> municipality_form_data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<query> queries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<edu_kind> edu_kind { get; set; }

        public override string ToString()
        {
            return name;
        }
    }
}
