//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduFormManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ownership_type{
        public ownership_type()
        {
            this.edus = new HashSet<edu>();
        }
    
        public int ownership_type_id { get; set; }
        public string name { get; set; }
    
    	public override string ToString() { return this.name; }
    
        public virtual ICollection<edu> edus { get; set; }
    }
}
