//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduFormManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class question{
        public question()
        {
            this.answers = new HashSet<answer>();
        }
    
        public int question_id { get; set; }
        public string question_title { get; set; }
        public Nullable<int> questionary_id { get; set; }
    
        public virtual ICollection<answer> answers { get; set; }
        public virtual questionary questionary { get; set; }
    }
}
