//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class credential{
        public credential()
        {
            this.queries = new HashSet<query>();
        }
    
        public string login { get; set; }
        public string passwd { get; set; }
        public int ref_id { get; set; }
        public int login_type { get; set; }
        public int credentials_id { get; set; }
    
        public virtual ICollection<query> queries { get; set; }
    }
}
