//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class message{
        public int message_id { get; set; }
        public string subject { get; set; }
        public string body { get; set; }
        public int from_edu_id { get; set; }
        public System.DateTime send_date { get; set; }
        public bool is_viewed { get; set; }
    
        public virtual edu edu { get; set; }
    }
}
