//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mm_regular__summary_form{
        public int regular_form_id { get; set; }
        public int summary_form_id { get; set; }
        public byte[] file_data { get; set; }
        public int id { get; set; }
    
        public virtual form regular_form { get; set; }
        public virtual form summary_form { get; set; }
    }
}
