//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class query{
        public int query_id { get; set; }
        public string title { get; set; }
        public int form_id { get; set; }
        public string content { get; set; }
        public int credentials_id { get; set; }
    
        public virtual credential credential { get; set; }
        public virtual form form { get; set; }

        public override string ToString()
        {
            return this.title;
        }
    }
}
