//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class questionary{
        public questionary()
        {
            this.questions = new HashSet<question>();
        }
    
        public int questionary_id { get; set; }
        public string questionary_title { get; set; }
    
        public virtual ICollection<question> questions { get; set; }
    }
}
