//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_detailed_municipality_form_statistics{
        public long row_id { get; set; }
        public int form_type_id { get; set; }
        public string form_type { get; set; }
        public string form { get; set; }
        public int form_id { get; set; }
        public int municipality_id { get; set; }
        public string municipality { get; set; }
        public int is_uploaded { get; set; }
        public int year { get; set; }
    }
}
